version: "3.8"

services:
  api:
    build: .
    container_name: cotrip_api
    depends_on:
      cotrip_db:
        condition: service_healthy
    ports:
      - "8084:8084"
    environment:
      COTRIP_DATABASE_USER: ${COTRIP_DATABASE_USER}
      COTRIP_DATABASE_PASSWORD: ${COTRIP_DATABASE_PASSWORD}
      COTRIP_DATABASE_HOST: ${COTRIP_DATABASE_HOST}
      COTRIP_DATABASE_PORT: ${COTRIP_DATABASE_PORT}
      COTRIP_DATABASE_NAME: ${COTRIP_DATABASE_NAME}
      COTRIP_SERVER_PORT: ${COTRIP_SERVER_PORT}
      COTRIP_SERVER_ENVIRONMENT: ${COTRIP_SERVER_ENVIRONMENT}
      COTRIP_MAIL_KEY: ${COTRIP_MAIL_KEY}
      COTRIP_MAIL_FROM: ${COTRIP_MAIL_FROM}
    networks:
      - cotrip_network
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"

  cotrip_db:
    image: postgres:17-alpine
    container_name: cotrip_db
    ports:
      - 5544:5432
    environment:
      POSTGRES_USER: ${COTRIP_DATABASE_USER}
      POSTGRES_PASSWORD: ${COTRIP_DATABASE_PASSWORD}
      POSTGRES_DB: ${COTRIP_DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cotrip_db_user_admin -d db_cotrip"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cotrip_network

networks:
  coolify:
    external: true
  cotrip_network:
    driver: bridge
