[database]
host = {{env "COTRIP_DATABASE_HOST"}}
port = {{env "COTRIP_DATABASE_PORT"}}
database = {{env "COTRIP_DATABASE_NAME"}}
user = {{env "COTRIP_DATABASE_USER"}}
password = {{env "COTRIP_DATABASE_PASSWORD"}}

