// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConfirmParticipant(ctx context.Context, id uuid.UUID) error
	CreateActivity(ctx context.Context, arg CreateActivityParams) (uuid.UUID, error)
	CreateTripLink(ctx context.Context, arg CreateTripLinkParams) (uuid.UUID, error)
	GetParticipant(ctx context.Context, id uuid.UUID) (Participant, error)
	GetParticipants(ctx context.Context, tripID uuid.UUID) ([]Participant, error)
	GetTrip(ctx context.Context, id uuid.UUID) (Trip, error)
	GetTripActivities(ctx context.Context, tripID uuid.UUID) ([]Activity, error)
	GetTripLinks(ctx context.Context, tripID uuid.UUID) ([]Link, error)
	InsertTrip(ctx context.Context, arg InsertTripParams) (uuid.UUID, error)
	InviteParticipantToTrip(ctx context.Context, arg InviteParticipantToTripParams) (uuid.UUID, error)
	InviteParticipantsToTrip(ctx context.Context, arg []InviteParticipantsToTripParams) (int64, error)
	UpdateTrip(ctx context.Context, arg UpdateTripParams) error
}

var _ Querier = (*Queries)(nil)
