// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pgstore/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/pgstore/querier.go -destination=internal/api/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pgstore "github.com/duddy57/cotrip-api/internal/pgstore"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// ConfirmParticipant mocks base method.
func (m *MockQuerier) ConfirmParticipant(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmParticipant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmParticipant indicates an expected call of ConfirmParticipant.
func (mr *MockQuerierMockRecorder) ConfirmParticipant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmParticipant", reflect.TypeOf((*MockQuerier)(nil).ConfirmParticipant), ctx, id)
}

// CreateActivity mocks base method.
func (m *MockQuerier) CreateActivity(ctx context.Context, arg pgstore.CreateActivityParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivity", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActivity indicates an expected call of CreateActivity.
func (mr *MockQuerierMockRecorder) CreateActivity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivity", reflect.TypeOf((*MockQuerier)(nil).CreateActivity), ctx, arg)
}

// CreateTripLink mocks base method.
func (m *MockQuerier) CreateTripLink(ctx context.Context, arg pgstore.CreateTripLinkParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTripLink", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTripLink indicates an expected call of CreateTripLink.
func (mr *MockQuerierMockRecorder) CreateTripLink(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTripLink", reflect.TypeOf((*MockQuerier)(nil).CreateTripLink), ctx, arg)
}

// GetParticipant mocks base method.
func (m *MockQuerier) GetParticipant(ctx context.Context, id uuid.UUID) (pgstore.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipant", ctx, id)
	ret0, _ := ret[0].(pgstore.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipant indicates an expected call of GetParticipant.
func (mr *MockQuerierMockRecorder) GetParticipant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipant", reflect.TypeOf((*MockQuerier)(nil).GetParticipant), ctx, id)
}

// GetParticipants mocks base method.
func (m *MockQuerier) GetParticipants(ctx context.Context, tripID uuid.UUID) ([]pgstore.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipants", ctx, tripID)
	ret0, _ := ret[0].([]pgstore.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipants indicates an expected call of GetParticipants.
func (mr *MockQuerierMockRecorder) GetParticipants(ctx, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipants", reflect.TypeOf((*MockQuerier)(nil).GetParticipants), ctx, tripID)
}

// GetTrip mocks base method.
func (m *MockQuerier) GetTrip(ctx context.Context, id uuid.UUID) (pgstore.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrip", ctx, id)
	ret0, _ := ret[0].(pgstore.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrip indicates an expected call of GetTrip.
func (mr *MockQuerierMockRecorder) GetTrip(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrip", reflect.TypeOf((*MockQuerier)(nil).GetTrip), ctx, id)
}

// GetTripActivities mocks base method.
func (m *MockQuerier) GetTripActivities(ctx context.Context, tripID uuid.UUID) ([]pgstore.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripActivities", ctx, tripID)
	ret0, _ := ret[0].([]pgstore.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripActivities indicates an expected call of GetTripActivities.
func (mr *MockQuerierMockRecorder) GetTripActivities(ctx, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripActivities", reflect.TypeOf((*MockQuerier)(nil).GetTripActivities), ctx, tripID)
}

// GetTripLinks mocks base method.
func (m *MockQuerier) GetTripLinks(ctx context.Context, tripID uuid.UUID) ([]pgstore.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripLinks", ctx, tripID)
	ret0, _ := ret[0].([]pgstore.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripLinks indicates an expected call of GetTripLinks.
func (mr *MockQuerierMockRecorder) GetTripLinks(ctx, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripLinks", reflect.TypeOf((*MockQuerier)(nil).GetTripLinks), ctx, tripID)
}

// InsertTrip mocks base method.
func (m *MockQuerier) InsertTrip(ctx context.Context, arg pgstore.InsertTripParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTrip", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTrip indicates an expected call of InsertTrip.
func (mr *MockQuerierMockRecorder) InsertTrip(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTrip", reflect.TypeOf((*MockQuerier)(nil).InsertTrip), ctx, arg)
}

// InviteParticipantToTrip mocks base method.
func (m *MockQuerier) InviteParticipantToTrip(ctx context.Context, arg pgstore.InviteParticipantToTripParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteParticipantToTrip", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InviteParticipantToTrip indicates an expected call of InviteParticipantToTrip.
func (mr *MockQuerierMockRecorder) InviteParticipantToTrip(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteParticipantToTrip", reflect.TypeOf((*MockQuerier)(nil).InviteParticipantToTrip), ctx, arg)
}

// InviteParticipantsToTrip mocks base method.
func (m *MockQuerier) InviteParticipantsToTrip(ctx context.Context, arg []pgstore.InviteParticipantsToTripParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteParticipantsToTrip", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InviteParticipantsToTrip indicates an expected call of InviteParticipantsToTrip.
func (mr *MockQuerierMockRecorder) InviteParticipantsToTrip(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteParticipantsToTrip", reflect.TypeOf((*MockQuerier)(nil).InviteParticipantsToTrip), ctx, arg)
}

// UpdateTrip mocks base method.
func (m *MockQuerier) UpdateTrip(ctx context.Context, arg pgstore.UpdateTripParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrip", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrip indicates an expected call of UpdateTrip.
func (mr *MockQuerierMockRecorder) UpdateTrip(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrip", reflect.TypeOf((*MockQuerier)(nil).UpdateTrip), ctx, arg)
}
